image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine

stages:
  - build
  - test
  - deploy


build:
  stage: build
  script:
  - "dotnet build"
  - "dotnet publish -c Release"

unit_tests:
  stage: test
  script:
  - "dotnet test"