name: dotnetcore
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Restore dotnet
      run: dotnet restore -s nuget.config
    - name: Build with dotnet
      working-directory: CloudToolsAPI
      run: dotnet build --configuration Release
    - name: Run Unit Test
      working-directory: CloudToolsUnitTesting
      run: dotnet test
