name: .Net Core

on: [push]

jobs:
  build:

    runs-on: alpine-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: |
          "dotnet build"
          "dotnet publish -c Release"
    - name: Run a multi-line script
      run: |
          "dotnet test"
